### ISSUE TITLE
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\config parser.py", line 788, in get

### ISSUE THREAD

**Issue by Arma-Software** [HA6Bots/TikTok-Compilation-Video-Generator#20]
Im getting a error while staring main.py
Anyone got a idea?

This is the full output:

C:\Users\Administrator\Downloads\TikTok-Compilation-Video-Generator-master\TikTo
k Server>py main.py
Found config in location C:\Users\Administrator\Downloads\TikTok-Compilation-Vid
eo-Generator-master\TikTok Server\config.ini
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\config
parser.py", line 788, in get
    value = d[option]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\collec
tions\__init__.py", line 914, in __getitem__
    return self.__missing__(key)            # support subclasses that define __m
issing__
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\collec
tions\__init__.py", line 906, in __missing__
    raise KeyError(key)
KeyError: 's_v_web_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import server
  File "C:\Users\Administrator\Downloads\TikTok-Compilation-Video-Generator-mast
er\TikTok Server\server.py", line 31, in <module>
    settings.generateConfigFile()
  File "C:\Users\Administrator\Downloads\TikTok-Compilation-Video-Generator-mast
er\TikTok Server\settings.py", line 75, in generateConfigFile
    loadValues()
  File "C:\Users\Administrator\Downloads\TikTok-Compilation-Video-Generator-mast
er\TikTok Server\settings.py", line 91, in loadValues
    s_v_web_id = config.get('tiktok', 's_v_web_id')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\config
parser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 's_v_web_id' in section: 'tiktok'

**Comment by ADH36** [comment]
Goto server folder 
Edit config.ini 

under [tiktok]
add
s_v_web_id = value
tt_webid = value

**Comment by Arma-Software** [comment]
Hi,

Thanks a lot gonna try this tonight.
Replace the value with an actual <value> or just the word?

**Comment by ADH36** [comment]
> Hi,
> 
> Thanks a lot gonna try this tonight.
> Replace the value with an actual "value" or just the word?

Actual Values !

I will dig into it more why it's happening .
For now seems like settings.py in unable to write temp config file .

**Comment by Arma-Software** [comment]
Thanks a lot.
Is there a wiki / readme where i can see how to get these vals?
Cheers

**Comment by ADH36** [comment]
Hey again , 

1-Goto tiktok website in chrome or any browser . For this instance I will consider chrome.

2-Login to your account . 

3-Open your profile .

4- Developer mode/tools .

5- In Top selection bar , Select application .

6- Find folder cookies . In cookies you can find both values just copy paste .

Will push nice readme , Soon .

**Comment by Arma-Software** [comment]
Works perfekt thanks a lot
-Closed
